"""create trip tables and add public sharing fields

Revision ID: 0565c6e95702
Revises: 27f9674f5184
Create Date: 2026-05-10 12:02:50.366643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0565c6e95702'
down_revision: Union[str, Sequence[str], None] = '27f9674f5184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('activities', 'category',
               existing_type=postgresql.ENUM('FLIGHT', 'HOTEL', 'FOOD', 'SIGHTSEEING', 'TRANSIT', 'OTHER', name='activitycategory'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('activities', 'cost_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_constraint(op.f('activities_stop_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'stops', ['stop_id'], ['id'])
    op.drop_index(op.f('ix_stops_id'), table_name='stops')
    op.drop_constraint(op.f('stops_trip_id_fkey'), 'stops', type_='foreignkey')
    op.create_foreign_key(None, 'stops', 'trips', ['trip_id'], ['id'])
    op.add_column('trips', sa.Column('public_link_id', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('trips', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.create_unique_constraint(None, 'trips', ['public_link_id'])
    op.drop_constraint(op.f('trips_user_id_fkey'), 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_user_id_fkey'), 'trips', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'trips', type_='unique')
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.alter_column('trips', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'public_link_id')
    op.drop_constraint(None, 'stops', type_='foreignkey')
    op.create_foreign_key(op.f('stops_trip_id_fkey'), 'stops', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_stops_id'), 'stops', ['id'], unique=False)
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_stop_id_fkey'), 'activities', 'stops', ['stop_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.alter_column('activities', 'cost_amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('activities', 'category',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FLIGHT', 'HOTEL', 'FOOD', 'SIGHTSEEING', 'TRANSIT', 'OTHER', name='activitycategory'),
               existing_nullable=False)
    op.drop_column('activities', 'notes')
    op.drop_column('activities', 'currency')
    # ### end Alembic commands ###
