"""add_purpose_to_otp

Revision ID: 86721b3c9944
Revises: fcf3d6e1dba1
Create Date: 2026-05-10 16:57:47.332593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86721b3c9944'
down_revision: Union[str, Sequence[str], None] = 'fcf3d6e1dba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_otps', sa.Column('purpose', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_otps', 'purpose')
    # ### end Alembic commands ###
