"""add_wishlist_otp_and_user_fields

Revision ID: fcf3d6e1dba1
Revises: 847f0ad981ca
Create Date: 2026-05-10 16:28:37.743654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf3d6e1dba1'
down_revision: Union[str, Sequence[str], None] = '847f0ad981ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('CITY', 'ACTIVITY', name='wishlistitemtype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_items_id'), 'wishlist_items', ['id'], unique=False)
    # Manual conversion for category to Enum
    op.execute("ALTER TABLE activities ALTER COLUMN category TYPE activitycategory USING category::activitycategory")

    op.alter_column('activities', 'cost_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.drop_constraint(op.f('activities_stop_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'stops', ['stop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activities', 'currency')
    op.drop_column('activities', 'notes')
    op.create_index(op.f('ix_stops_id'), 'stops', ['id'], unique=False)
    op.drop_constraint(op.f('stops_trip_id_fkey'), 'stops', type_='foreignkey')
    op.create_foreign_key(None, 'stops', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trips', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.drop_constraint(op.f('trips_user_id_fkey'), 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('additional_details', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'additional_details')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'mobile_number')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_user_id_fkey'), 'trips', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.alter_column('trips', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'stops', type_='foreignkey')
    op.create_foreign_key(op.f('stops_trip_id_fkey'), 'stops', 'trips', ['trip_id'], ['id'])
    op.drop_index(op.f('ix_stops_id'), table_name='stops')
    op.add_column('activities', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_stop_id_fkey'), 'activities', 'stops', ['stop_id'], ['id'])
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.alter_column('activities', 'cost_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('activities', 'category',
               existing_type=sa.Enum('FLIGHT', 'HOTEL', 'FOOD', 'SIGHTSEEING', 'TRANSIT', 'OTHER', name='activitycategory'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_wishlist_items_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_table('user_otps')
    # ### end Alembic commands ###
